apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: simple-quote-app
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000  # External port
      targetPort: 3000  # Container port
      nodePort: 32300
  type: NodePort  # For external access